# Generated by Django 5.2.3 on 2025-07-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_chaivarity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivarity',
            name='image',
            field=models.ImageField(upload_to='myapps/'),
        ),
    ]
